EWPP-2986: Drupal 10 compatibility.
openeuropa/oe_dashboard_agent pull request #21
Opened 2023-02-09 17:44 UTC by brummbar

2023-02-13 13:56 UTC, drishu submitted a review, later dismissed

2023-02-15 21:45 UTC, claudiu-cristea approved these changes

2023-02-16 15:38 UTC, drishu approved these changes

2023-02-17 08:05 UTC, drishu requested changes
noticed this only today in other PR, sry

2023-02-17 08:05 UTC, drishu commented on .drone.yml
> +      - composer require drupal/core:^${CORE_VERSION} drupal/core-composer-scaffold:^${CORE_VERSION} --update-with-all-dependencies --ansi --no-progress --no-interaction
```suggestion
      - composer require drupal/core:~${CORE_VERSION} drupal/core-composer-scaffold:~${CORE_VERSION} --update-with-all-dependencies --ansi --no-progress --no-interaction
```

2023-02-17 08:05 UTC, drishu commented on .drone.yml
> +    - CORE_VERSION: 9.4
```suggestion
    - CORE_VERSION: 9.4.0
```

2023-02-17 08:05 UTC, drishu commented on .drone.yml
> +    - CORE_VERSION: 9.4
```suggestion
    - CORE_VERSION: 9.4.0
```

2023-02-17 14:34 UTC, drishu approved these changes

2023-02-21 18:11 UTC, sergepavle approved these changes

2023-02-22 14:39 UTC, merged